name: kdp pipeline

on:
  workflow_dispatch: # Add manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Copy KDP assets to folder
      run: | 
          mkdir book
          cp -r assets/kdp/* book/
          mv book/introduction.md book/01.md
          ls -alh book
          
    - name: extract chapters
      run: |
        
        cp 03_commandline/01_course.md book/03.md
        cp 04_filesandfolders/01_course.md book/04.md
        cp 05_filecontents/01_course.md book/05.md
        cp 06_software/01_course.md book/06.md
        cp 07_advancedcommands/01_course.md book/07.md
        cp 08_filters/01_course.md book/08.md
        cp 09_usersandgroups/01_course.md book/09.md
        cp 10_permissions/01_course.md book/10.md
        cp 11_automation/01_course.md book/11.md
        cp -R images book/
          
    - name: Replace blocks in Markdown files
      run: |
        find book -name "*.md" -print0 | xargs -0 sed -i 's/\?> \(.*\)/<span class="highlight">\1<\/span>/g'
    - name: Update image paths in Markdown files
      run: |
         find book -name "*.md" -print0 | xargs -0 sed -i 's|(\.\./images/|(./images/|g'
    - name: Update image paths in Markdown files
      run: |
        find . -name "*.md" -exec sed -i 's|\(!\[.*\](\./images/[0-9]\+/\(.*\....?\))\)|\1{#myimg}|g' {} +


    - name: Remove specific HTML tag from Markdown files
      run: |
          find book -name "*.md" -print0 | xargs -0 sed -i 's_<i class="fa-solid fa-circle-info"><\/i>__g'
          find book -name "*.md" -print0 | xargs -0 sed -i 's_<i class="fa-solid fa-earth-europe"></i>__g'

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
    - name: Convert Markdown
      run: |
         cd book
         pandoc --listings -o book.epub metadata.yml *.md -d config.yml  --css=stylesheet.css --no-highlight
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: kdp-artifact
        path: book
